import Head from "next/head";
import { FC } from "react";
import Layout from "../../components/Layout";
import Title from "../../components/UI/Title";

type Props = {};

const CV: FC<Props> = ({}) => {
  return (
    <>
      <Head>
        <title>Резюме</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Title>Резюме</Title>
      </Layout>
    </>
  );
};

export default CV;
