import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import { GetStaticProps } from "next";
import Head from "next/head";
import { FC } from "react";
import Layout from "../../components/Layout";
import Text from "../../components/UI/Text";
import Title from "../../components/UI/Title";
import client from "../../contentful";
import { ICv, ICvFields } from "../../contentful/contentful";

type Props = {
  resume: ICv;
};

const CV: FC<Props> = ({ resume }) => {
  return (
    <>
      <Head>
        <title>Резюме</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Title>{resume.fields.title}</Title>
        <Text>{documentToReactComponents(resume.fields.text!)}</Text>
      </Layout>
    </>
  );
};

export default CV;

export const getStaticProps: GetStaticProps = async () => {
  const CV = await client.getEntries<ICvFields>({
    content_type: "cv",
  });

  const [CVPage] = CV.items;

  return {
    props: {
      resume: CVPage,
    },
    revalidate: 3600,
  };
};
