import { GetStaticProps } from "next";
import Head from "next/head";
import React, { FC } from "react";
import Layout from "../../components/Layout";
import Card from "../../components/UI/Card";
import Title from "../../components/UI/Title";
import Wrapper from "../../components/UI/Wrapper";
import client from "../../contentful";
import { IArticle, IArticleFields } from "../../contentful/contentful";

type Props = {
  articles: IArticle[];
};

const Blog: FC<Props> = ({ articles }) => {
  return (
    <>
      <Head>
        <title>Последние записи</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Title>Последние записи</Title>
        <Wrapper>
          {articles.map((item) => (
            <Card
              key={item.fields.slug}
              link={`/Articles/${item.fields.slug}`}
              title={item.fields.title}
              text={item.fields.description!}
            />
          ))}
        </Wrapper>
      </Layout>
    </>
  );
};

export default Blog;

export const getStaticProps: GetStaticProps = async () => {
  const articleEntries = await client.getEntries<IArticleFields>({
    content_type: "Article",
    select: "fields.title,fields.description,fields.slug",
  });

  return {
    props: {
      articles: articleEntries.items,
    },
    revalidate: 3600,
  };
};
