import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Card from "../components/UI/Card";
import Title from "../components/UI/Title";
import Wrapper from "../components/UI/Wrapper";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Title>Последние записи</Title>
        <Wrapper>
          <Card
            link="/"
            title="Lorem ipsum dolor"
            text="Natus iusto
          autem odit omnis animi provident ullam perspiciatis qui. Consequuntur et
          ipsam sunt deserunt! Deserunt tenetur rem enim assumenda atque eveniet."
          />
          <Card
            link="/"
            title="Lorem ipsum dolor"
            text="Natus iusto
          autem odit omnis animi provident ullam perspiciatis qui. Consequuntur et
          ipsam sunt deserunt! Deserunt tenetur rem enim assumenda atque eveniet."
          />
          <Card
            link="/"
            title="Lorem ipsum dolor"
            text="Natus iusto
          autem odit omnis animi provident ullam perspiciatis qui. Consequuntur et
          ipsam sunt deserunt! Deserunt tenetur rem enim assumenda atque eveniet."
          />
          <Card
            link="/"
            title="Lorem ipsum dolor"
            text="Natus iusto
          autem odit omnis animi provident ullam perspiciatis qui. Consequuntur et
          ipsam sunt deserunt! Deserunt tenetur rem enim assumenda atque eveniet."
          />
        </Wrapper>
      </Layout>
    </div>
  );
};

export default Home;
